/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiKeyRouteImport } from './routes/_authenticated/api-key'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicScanSessionRouteImport } from './routes/api/public/scan/session'
import { Route as ApiPublicScanAuthorizeRouteImport } from './routes/api/public/scan/authorize'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicScanSessionRefreshRouteImport } from './routes/api/public/scan/session.refresh'

const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeyRoute = AuthenticatedApiKeyRouteImport.update({
  id: '/api-key',
  path: '/api-key',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicScanSessionRoute = ApiPublicScanSessionRouteImport.update({
  id: '/api/public/scan/session',
  path: '/api/public/scan/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanAuthorizeRoute = ApiPublicScanAuthorizeRouteImport.update({
  id: '/api/public/scan/authorize',
  path: '/api/public/scan/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScanSessionRefreshRoute =
  ApiPublicScanSessionRefreshRouteImport.update({
    id: '/refresh',
    path: '/refresh',
    getParentRoute: () => ApiPublicScanSessionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/api-key': typeof AuthenticatedApiKeyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scan/authorize': typeof ApiPublicScanAuthorizeRoute
  '/api/public/scan/session': typeof ApiPublicScanSessionRouteWithChildren
  '/api/public/scan/session/refresh': typeof ApiPublicScanSessionRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/api-key': typeof AuthenticatedApiKeyRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scan/authorize': typeof ApiPublicScanAuthorizeRoute
  '/api/public/scan/session': typeof ApiPublicScanSessionRouteWithChildren
  '/api/public/scan/session/refresh': typeof ApiPublicScanSessionRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/legal': typeof LegalRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/api-key': typeof AuthenticatedApiKeyRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scan/authorize': typeof ApiPublicScanAuthorizeRoute
  '/api/public/scan/session': typeof ApiPublicScanSessionRouteWithChildren
  '/api/public/scan/session/refresh': typeof ApiPublicScanSessionRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/legal'
    | '/admin'
    | '/api-key'
    | '/billing'
    | '/dashboard'
    | '/devices'
    | '/feedback'
    | '/settings'
    | '/support'
    | '/blog/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/api/public/payments/webhook'
    | '/api/public/scan/authorize'
    | '/api/public/scan/session'
    | '/api/public/scan/session/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/legal'
    | '/admin'
    | '/api-key'
    | '/billing'
    | '/dashboard'
    | '/devices'
    | '/feedback'
    | '/settings'
    | '/support'
    | '/blog/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/api/public/payments/webhook'
    | '/api/public/scan/authorize'
    | '/api/public/scan/session'
    | '/api/public/scan/session/refresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/legal'
    | '/_authenticated/admin'
    | '/_authenticated/api-key'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/feedback'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/blog/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/api/public/payments/webhook'
    | '/api/public/scan/authorize'
    | '/api/public/scan/session'
    | '/api/public/scan/session/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  LegalRoute: typeof LegalRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicScanAuthorizeRoute: typeof ApiPublicScanAuthorizeRoute
  ApiPublicScanSessionRoute: typeof ApiPublicScanSessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-key': {
      id: '/_authenticated/api-key'
      path: '/api-key'
      fullPath: '/api-key'
      preLoaderRoute: typeof AuthenticatedApiKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/scan/session': {
      id: '/api/public/scan/session'
      path: '/api/public/scan/session'
      fullPath: '/api/public/scan/session'
      preLoaderRoute: typeof ApiPublicScanSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan/authorize': {
      id: '/api/public/scan/authorize'
      path: '/api/public/scan/authorize'
      fullPath: '/api/public/scan/authorize'
      preLoaderRoute: typeof ApiPublicScanAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan/session/refresh': {
      id: '/api/public/scan/session/refresh'
      path: '/refresh'
      fullPath: '/api/public/scan/session/refresh'
      preLoaderRoute: typeof ApiPublicScanSessionRefreshRouteImport
      parentRoute: typeof ApiPublicScanSessionRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApiKeyRoute: typeof AuthenticatedApiKeyRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApiKeyRoute: AuthenticatedApiKeyRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LegalRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface ApiPublicScanSessionRouteChildren {
  ApiPublicScanSessionRefreshRoute: typeof ApiPublicScanSessionRefreshRoute
}

const ApiPublicScanSessionRouteChildren: ApiPublicScanSessionRouteChildren = {
  ApiPublicScanSessionRefreshRoute: ApiPublicScanSessionRefreshRoute,
}

const ApiPublicScanSessionRouteWithChildren =
  ApiPublicScanSessionRoute._addFileChildren(ApiPublicScanSessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  LegalRoute: LegalRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicScanAuthorizeRoute: ApiPublicScanAuthorizeRoute,
  ApiPublicScanSessionRoute: ApiPublicScanSessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
